### ISSUE TITLE
vim : set invnumber not working with set relativenumber

### ISSUE THREAD

**Issue by gutelfuldead** [jordanfwoods/dotfiles#1]
When NOT using relative number `:set invnumber` can be used to toggle the line numbers on the side of the screen on and off. When `set relativenumber` IS used then this no longer works; it instead will just change the current line number to 0 and leave the rest of the fields present. 

Ideally can use the combination in .vimrc

```
set relativenumber
noremap <F2> :set invnumber<CR>
```
Stop slacking.

**Comment by gutelfuldead** [comment]
bump

**Comment by jordanfwoods** [comment]
Added. I use <leader><F12> to flip number, relative number, and paste so I can copy paste easier, but this also pretty helpful
